### ISSUE TITLE
Bluetooth keyboard doesn't work

### ISSUE THREAD

**Issue by michaelchany** [jacobcxdev/FBSpNOsor#4]
Facebook: 263
iPhone12,8 (A2275)
IOS 13.6
Jailbreak: Odyssey with Sileo 2.0.0

I've been having a recurring issue lately with the keyboard not reliably working in the Facebook app.  

I'd put my cursor in a comment box and it would just never work or would take multiple attempts and still might never work.  I could change the volume and do all of the other BT functions, but not typing, and I also couldn't show or hide the virtual keyboard,

I uninstalled and reinstalled the app a bunch of times.  I even submitted screen recordings of it happening to the FB team.  Just now, however, I uninstalled FBSpNOsor, and the keyboard now works perfectly.

**Comment by jacobcxdev** [comment]
I would guess that this is purely coincidental; if you look at the [source code](https://github.com/jacobcxdev/FBSpNOsor/blob/master/Tweak.x), you'll see that I don't touch any HID stuff at all. It may be an issue with the jailbreak itself when injecting tweaks into Facebook — try installing a different Facebook tweak while FBSpNOSor is disabled; does the issue still occur? If so, the issue is likely with libhooker; if not, then I have no idea what the cause might be.

Sorry for the inconvenience.

**Comment by michaelchany** [comment]
I did some further testing and it does seem related to the jailbreak.  No issues at all with my other devices on unc0ver.  Just my iPhone on Odyssey.  I even updated libhooker (update pushed out yesterday) but it didn't change anything.  Is there any way to mitigate this issue?

**Comment by jacobcxdev** [comment]
> Is there any way to mitigate this issue?

No idea, sorry!
